import {administrationRequest} from './Administration';
import {useState} from 'react';
import {useQuery, useMutation, useQueryClient} from '@tanstack/react-query';
import {teamRequest, useTeam, type TeamUser} from '../contexts/TeamContext';
import {localDateTime} from '../utils/dateTime';
const input = 'block w-full bg-navy-800 border border-navy-600 rounded p-2 text-white';
const button = 'bg-brand-500 text-white rounded px-3 py-2 disabled:opacity-40';
type Member = {workspace_id: string; user_id: string; role: string};
type Audit = {id: number; actor_name: string; action: string; target_id: string; created_at: string; details: Record<string, unknown>};

export function AuditHistory({targetId, admin=false}: {targetId?: string; admin?: boolean}) {
  const team = useTeam(), [before, setBefore] = useState<number>();
  const path = admin ? '/admin-audit' : '/audit';
  const params = new URLSearchParams();if (targetId) params.set('target_id',targetId);if (before) params.set('before',String(before));
  const result = useQuery({queryKey: ['audit',team.workspace_id,targetId,admin,before], queryFn: () => teamRequest<Audit[]>(path+'?'+params), enabled: team.enabled});
  if (!team.enabled) return null;
  return <section className="space-y-3"><h2 className="font-semibold text-white">Audit history</h2><p className="text-xs text-gray-400">Records who changed which fields. Passwords, source text, and reviewer note contents are excluded.</p>
    {result.error && <p role="alert" className="text-red-400">{result.error.message}</p>}
    <ol className="space-y-2">{result.data?.map(e => <li key={e.id} className="text-xs text-gray-400 border-b border-navy-600 pb-2">{localDateTime(e.created_at)} · <strong>{e.actor_name}</strong> · {e.action}<br />{e.target_id} · {JSON.stringify(e.details)}</li>)}</ol>
    {result.data?.length === 0 && <p className="text-gray-400">No events recorded.</p>}
    <button className="underline text-brand-500" onClick={() => {setBefore(undefined);result.refetch();}}>Latest events</button>
    {result.data?.length === 100 && <button className="ml-3 underline text-brand-500" onClick={() => setBefore(result.data![result.data!.length - 1].id)}>Older events</button>}
  </section>;
}

export default function Account() {
  const team = useTeam(), qc = useQueryClient();
  const [current, setCurrent] = useState(''), [password, setPassword] = useState(''), [message, setMessage] = useState('');
  const [username, setUsername] = useState(''), [newPassword, setNewPassword] = useState(''), [admin, setAdmin] = useState(false), [workspace, setWorkspace] = useState('');
  const [memberUser, setMemberUser] = useState(''), [memberSpace, setMemberSpace] = useState(''), [role, setRole] = useState('reviewer');
  const [resetUser, setResetUser] = useState(''), [resetPassword, setResetPassword] = useState('');
  const users = useQuery({queryKey:['users'],queryFn:()=>teamRequest<TeamUser[]>('/users'),enabled:!!team.user?.is_admin});
  const profiles = useQuery({queryKey:['administration','profiles'],queryFn:()=>administrationRequest<{profiles:{id:string;name:string;builtin:boolean}[]}>('/profiles'),enabled:!!team.user?.is_admin});
  const memberships = useQuery({queryKey:['memberships'],queryFn:()=>teamRequest<Member[]>('/memberships'),enabled:!!team.user?.is_admin});
  const mutation = useMutation({mutationFn: (task:()=>Promise<unknown>)=>task(),onSuccess:()=>{setMessage('Saved.');qc.invalidateQueries({queryKey:['auth']});qc.invalidateQueries({queryKey:['users']});qc.invalidateQueries({queryKey:['memberships']});qc.invalidateQueries({queryKey:['audit']});}});
  if (!team.enabled) return <p className="p-6 text-gray-400">Named accounts are not enabled on this installation.</p>;
  return <div className="max-w-screen-lg mx-auto p-6 space-y-6"><h1 className="text-2xl text-white font-semibold">Account & access</h1><p className="text-gray-300">Change your password here. Administrators can also manage people, customer workspaces, permissions, and audit history.</p>
    {message && <p role="status" className="text-emerald-500">{message}</p>}{mutation.error && <p role="alert" className="text-red-400">{mutation.error.message}</p>}
    <form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate(async()=>{await teamRequest('/password','POST',{current_password:current,new_password:password});setCurrent('');setPassword('');});}}><h2 className="font-semibold text-white">Change your password</h2><label className="block text-gray-400">Current password<input className={input} type="password" autoComplete="current-password" required value={current} onChange={e=>setCurrent(e.target.value)} /></label><label className="block text-gray-400">New password (14–256 characters)<input className={input} type="password" autoComplete="new-password" minLength={14} maxLength={256} required value={password} onChange={e=>setPassword(e.target.value)} /></label><button className={button} disabled={mutation.isPending}>Change password</button></form>
    {team.user?.is_admin && <>
      <form className="border-t border-navy-600 pt-4 space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate(async()=>{await teamRequest('/users','POST',{username,password:newPassword,is_admin:admin});setUsername('');setNewPassword('');});}}><h2 className="font-semibold text-white">Create account</h2><label className="block text-gray-400">New username<input className={input} value={username} maxLength={80} required onChange={e=>setUsername(e.target.value)} /></label><label className="block text-gray-400">Initial password<input className={input} type="password" autoComplete="new-password" minLength={14} maxLength={256} required value={newPassword} onChange={e=>setNewPassword(e.target.value)} /></label><label className="block text-gray-400"><input type="checkbox" checked={admin} onChange={e=>setAdmin(e.target.checked)} /> Installation administrator (all customers)</label><p className="text-xs text-gray-400">Share credentials directly through your approved secure channel. Account credentials are never sent automatically by email. Non-admin accounts need a workspace assignment.</p><button className={button} disabled={mutation.isPending}>Create account</button></form>
      <section className="space-y-2"><h2 className="font-semibold text-white">Accounts</h2>{users.error && <p role="alert">{users.error.message}</p>}{users.data?.map(u=><div className="flex flex-wrap gap-3 text-gray-300" key={u.id}><span className="flex-1">{u.username} · {u.is_admin?'Administrator':'Workspace member'} · {u.active?'Active':'Disabled'}</span><button disabled={mutation.isPending} className="underline" onClick={()=>mutation.mutate(()=>teamRequest('/users/'+u.id,'PUT',{active:!u.active,is_admin:u.is_admin}))}>{u.active?'Disable':'Enable'}</button><button disabled={mutation.isPending} className="underline" onClick={()=>{if(window.confirm(`Change administrator access for ${u.username}? All their sessions will end.`)) mutation.mutate(()=>teamRequest('/users/'+u.id,'PUT',{active:u.active,is_admin:!u.is_admin}));}}>{u.is_admin?'Remove admin':'Make admin'}</button></div>)}</section>
      <form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate(async()=>{await teamRequest('/workspaces','POST',{name:workspace});setWorkspace('');});}}><label className="block text-gray-400">New customer workspace<input className={input} value={workspace} maxLength={160} required onChange={e=>setWorkspace(e.target.value)} /></label><button className={button} disabled={mutation.isPending}>Create workspace</button></form>
      <form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate(()=>teamRequest('/memberships','PUT',{user_id:memberUser,workspace_id:memberSpace,role}));}}><h2 className="font-semibold text-white">Assign workspace access</h2><label className="block text-gray-400">Account<select aria-label="Account" className={input} value={memberUser} required onChange={e=>setMemberUser(e.target.value)}><option value="">Choose account</option>{users.data?.filter(u=>!u.is_admin).map(u=><option key={u.id} value={u.id}>{u.username}</option>)}</select></label><label className="block text-gray-400">Workspace<select aria-label="Workspace" className={input} value={memberSpace} required onChange={e=>setMemberSpace(e.target.value)}><option value="">Choose workspace</option>{team.workspaces?.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="block text-gray-400">Role<select aria-label="Role" className={input} value={role} onChange={e=>setRole(e.target.value)}><option value="reviewer">Reviewer — read and edit</option><option value="viewer">Viewer — read and export</option>{profiles.data?.profiles.filter(p=>!p.builtin).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className={button} disabled={mutation.isPending}>Save workspace access</button></form>
      <div className="space-y-2">{memberships.data?.map(m=><div className="flex gap-3 text-gray-400" key={m.workspace_id+m.user_id}><span className="flex-1">{users.data?.find(u=>u.id===m.user_id)?.username} · {team.workspaces?.find(w=>w.id===m.workspace_id)?.name} · {m.role}</span><button disabled={mutation.isPending} className="underline text-red-400" onClick={()=>mutation.mutate(()=>teamRequest(`/memberships/${m.workspace_id}/${m.user_id}`,'DELETE'))}>Revoke access</button></div>)}</div>
      <form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate(async()=>{await teamRequest('/users/'+resetUser+'/password','POST',{new_password:resetPassword});setResetPassword('');});}}><h2 className="text-white font-semibold">Reset account password</h2><select aria-label="Account to reset" className={input} required value={resetUser} onChange={e=>setResetUser(e.target.value)}><option value="">Choose account</option>{users.data?.map(u=><option key={u.id} value={u.id}>{u.username}</option>)}</select><input aria-label="Replacement password" className={input} type="password" autoComplete="new-password" minLength={14} maxLength={256} required value={resetPassword} onChange={e=>setResetPassword(e.target.value)} /><button className={button} disabled={mutation.isPending}>Reset password and end sessions</button></form>
    </>}
    <AuditHistory admin={!!team.user?.is_admin} />
  </div>;
}
