import {useState} from 'react';
import {Link} from 'react-router-dom';
import SourceContent from '../components/dashboard/SourceContent';
import {saveDownload} from '../utils/sessionZip';
import {generateHtml,getAvailableSections} from '../utils/htmlExport';
import type {JobDetail} from '../types';
const notes=[{id:'EXAMPLE-101',version:'7.6.5',text:'**Synthetic example:** After an interface change, verify that monitoring checks use the intended source interface.'},{id:'EXAMPLE-101',version:'7.6.6',text:'**Synthetic example:** After an interface change, verify that monitoring checks use the intended source interface.'},{id:'EXAMPLE-202',version:'7.6.6',text:'**Synthetic example:** A new diagnostic command displays the last successful health check.'}];
export default function Example(){const [search,setSearch]=useState(''),[consolidate,setConsolidate]=useState(false);const rows=notes.filter(n=>`${n.id} ${n.text} ${n.version}`.toLowerCase().includes(search.toLowerCase()));const grouped=consolidate?rows.filter((n,i)=>rows.findIndex(x=>x.id===n.id&&x.text===n.text)===i):rows;
 const job:JobDetail={id:'synthetic-example',from_version:'7.6.5',to_version:'7.6.6',created_at:'2026-09-12T00:00:00',status:'completed',use_selenium:false,versions:['7.6.5','7.6.6'],warnings:['Synthetic demonstration only. These are not Fortinet release notes.'],all_data:Object.fromEntries(['7.6.5','7.6.6'].map(v=>[v,{known_issues:notes.filter(n=>n.version===v).map(n=>({'Bug ID':n.id,category:'Example',Description:n.text,markdown:n.text}))}])),localConsolidation:consolidate?['known_issues']:[]};
 return <div className="max-w-screen-xl mx-auto p-6 space-y-5"><h1 className="text-3xl font-semibold text-white">Explore an example report</h1><p className="rounded border border-amber-500 p-3 text-amber-400">Synthetic demonstration — invented notes, not Fortinet documentation or upgrade advice. Nothing is imported into your session.</p><div className="flex flex-wrap gap-4"><input aria-label="Search example" className="rounded bg-navy-800 border border-navy-600 p-3 text-white" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search example notes"/><label className="text-gray-300 flex gap-2 items-center"><input type="checkbox" checked={consolidate} onChange={e=>setConsolidate(e.target.checked)}/>Consolidate identical notes</label></div>{grouped.map((n,i)=><article key={i} className="rounded-xl bg-navy-800 border border-navy-600 p-5 text-gray-300"><h2 className="font-semibold text-white">{n.id} · {(consolidate?rows.filter(x=>x.id===n.id&&x.text===n.text).map(x=>x.version):[n.version]).join(', ')}</h2><SourceContent markdown={n.text}/></article>)}<button className="rounded bg-brand-500 p-3 text-white" onClick={()=>saveDownload(new Blob([generateHtml(job,new Set(getAvailableSections(job).map(x=>x.id)))],{type:'text/html'}),'synthetic-example.html')}>Download full example report</button><Link to="/#import" className="ml-4 text-brand-500 underline">Try your own PDFs</Link></div>
}
